packages:
  - "clawdbot"
  - "browser-use"
  - "planning-with-files"
  - "antigravity-awesome-skills"
  - "antigravity-manager"
  - "ui-ux-pro-max"
  - "copilotkit"
  - "workspace-template"
  - "cherry-studio"
  - "animate-css"
  - "cline"
  - "guru-gateway"
  - "apps/*"
  - "packages/*"
